/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Security
{
	public static class QOPHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(QOPHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateEnumTc(Security.QOPHelper.Id(),"QOP", new String[] {"SecQOPNoProtection", "SecQOPIntegrity", "SecQOPConfidentiality", "SecQOPIntegrityAndConfidentiality"});
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Security.QOP value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static Security.QOP Extract(CORBA.Any any)
		{
				var inputStream = any.CreateInputStream();
			try
			{
			return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/Security/QOP:1.0";
		}

		public static Security.QOP Read(CORBA.IInputStream inputStream)
		{
			return (Security.QOP) inputStream.ReadLong();
		}

		public static void Write(CORBA.IOutputStream outputStream, Security.QOP value)
		{
			outputStream.WriteLong((int) value);
		}

	}
}
