/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace Security
{
	[RepositoryID("IDL:omg.org/Security/Right:1.0")]
	[Helper(typeof(RightHelper))]
	public partial class Right: CORBA.IIDLEntity, IEquatable<Security.Right>
	{
		[IdlName("Right")]
		public Security.ExtensibleFamily RightsFamily { get; set; }
		[IdlName("Right")]
		[WideChar(false)]
		public string _Right { get; set; }

		public Right()
		{
		}

		public Right(Right other)
		{
			RightsFamily = other.RightsFamily;
			_Right = other._Right;
		}

		public Right(Security.ExtensibleFamily rightsFamily, string right)
		{
			this.RightsFamily = rightsFamily;
			this._Right = right;
		}

		public bool Equals(Security.Right? other)
		{
			if (other == null) return false;
			if (!RightsFamily.Equals(other.RightsFamily)) return false;
			if (!_Right.Equals(other._Right)) return false;
			return true;
		}
	}

}
