/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ETF
{
	public interface IHandleOperations
	{
		[IdlName("add_input")]
		public bool AddInput(ETF.IConnection conn);
		[IdlName("signal_data_available")]
		public void SignalDataAvailable(ETF.IConnection conn);
		[IdlName("closed_by_peer")]
		public void ClosedByPeer(ETF.IConnection conn);
	}
}

