/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ETF
{
		public static class ListenerHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(ListenerHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateLocalInterfaceTc("IDL:omg.org/ETF/Listener:1.0", "Listener");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, ETF.IListener ifz)
			{
				any.InsertObject(ifz);
			}

			public static ETF.IListener Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:omg.org/ETF/Listener:1.0";
			}

			public static ETF.IListener Read(CORBA.IInputStream inputStream)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static void Write(CORBA.IOutputStream outputStream, ETF.IListener ifz)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static ETF.IListener Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is ETF.IListener)
				{
					return (ETF.IListener)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static ETF.IListener UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is ETF.IListener)
				{
					return (ETF.IListener)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}
		}
}
