/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace DynamicAny
{
	public interface IDynValueOperations : DynamicAny.IDynValueCommonOperations
	{
		[IdlName("current_member_name")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.TypeMismatch))]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		[return: WideChar(false)]
		public string CurrentMemberName();
		[IdlName("current_member_kind")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.TypeMismatch))]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		public CORBA.TCKind CurrentMemberKind();
		[IdlName("get_members")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		public DynamicAny.NameValuePair[] GetMembers();
		[IdlName("set_members")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.TypeMismatch))]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		public void SetMembers(DynamicAny.NameValuePair[] value);
		[IdlName("get_members_as_dyn_any")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		public DynamicAny.NameDynAnyPair[] GetMembersAsDynAny();
		[IdlName("set_members_as_dyn_any")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.TypeMismatch))]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		public void SetMembersAsDynAny(DynamicAny.NameDynAnyPair[] value);
	}
}

