/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:33
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace Messaging
{
	[IdlName("REPLY_START_TIME_POLICY_TYPE")]
	public sealed class REPLY_START_TIME_POLICY_TYPE
	{
		public const uint Value = 29;
	}
}
