/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:30
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace PortableGroup
{
	[RepositoryID("IDL:omg.org/PortableGroup/Property:1.0")]
	[Helper(typeof(PropertyHelper))]
	public partial class Property: CORBA.IIDLEntity, IEquatable<PortableGroup.Property>
	{
		[IdlName("Property")]
		public CosNaming.NameComponent[] Nam { get; set; }
		[IdlName("Property")]
		public CORBA.Any Val { get; set; }

		public Property()
		{
		}

		public Property(Property other)
		{
			Nam = other.Nam;
			Val = other.Val;
		}

		public Property(CosNaming.NameComponent[] nam, CORBA.Any val)
		{
			this.Nam = nam;
			this.Val = val;
		}

		public bool Equals(PortableGroup.Property? other)
		{
			if (other == null) return false;
			if (!Nam.SequenceEqual(other.Nam)) return false;
			if (!Val.Equals(other.Val)) return false;
			return true;
		}
	}

}
