/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:30
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableGroup
{
	public static class ValueHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ValueHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(PortableGroup.ValueHelper.Id(), "Value", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 11));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, CORBA.Any value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static CORBA.Any Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/PortableGroup/Value:1.0";
		}

		public static CORBA.Any Read(CORBA.IInputStream inputStream)
		{
			CORBA.Any result;
			result = inputStream.ReadAny();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, CORBA.Any value)
		{
			outputStream.WriteAny(value);
		}

	}
}
