/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{
	public abstract class _ServantLocatorLocalBase: CORBA.LocalObject, IServantLocator
	{
		private string[] _ids = {"IDL:PortableServer/ServantLocator:1.0","IDL:PortableServer/ServantManager:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("preinvoke")]
		[ThrowsIdlException(typeof(PortableServer.ForwardRequest))]
		public abstract PortableServer.Servant Preinvoke(byte[] oid, PortableServer.IPOA adapter, [WideChar(false)] string operation, out PortableServer.ServantLocator.Cookie theCookie);
		[IdlName("postinvoke")]
		public abstract void Postinvoke(byte[] oid, PortableServer.IPOA adapter, [WideChar(false)] string operation, PortableServer.ServantLocator.Cookie theCookie, PortableServer.Servant theServant);
	}

}
