/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{
	public interface IServantActivatorOperations : PortableServer.IServantManagerOperations
	{
		[IdlName("incarnate")]
		[ThrowsIdlException(typeof(PortableServer.ForwardRequest))]
		public PortableServer.Servant Incarnate(byte[] oid, PortableServer.IPOA adapter);
		[IdlName("etherealize")]
		public void Etherealize(byte[] oid, PortableServer.IPOA adapter, PortableServer.Servant serv, bool cleanupInProgress, bool remainingActivations);
	}
}

