/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{

	public class POAManagerLocalTie: _POAManagerLocalBase
	{
		public IPOAManagerOperations _OperationsDelegate { get; set; }

		public POAManagerLocalTie(IPOAManagerOperations d)
		{
			_OperationsDelegate = d;
		}

		[IdlName("activate")]
		[ThrowsIdlException(typeof(PortableServer.POAManager.AdapterInactive))]
		public override void Activate()
		{
			_OperationsDelegate.Activate();
		}
		[IdlName("hold_requests")]
		[ThrowsIdlException(typeof(PortableServer.POAManager.AdapterInactive))]
		public override void HoldRequests(bool waitForCompletion)
		{
			_OperationsDelegate.HoldRequests(waitForCompletion);
		}
		[IdlName("discard_requests")]
		[ThrowsIdlException(typeof(PortableServer.POAManager.AdapterInactive))]
		public override void DiscardRequests(bool waitForCompletion)
		{
			_OperationsDelegate.DiscardRequests(waitForCompletion);
		}
		[IdlName("deactivate")]
		public override void Deactivate(bool etherealizeObjects, bool waitForCompletion)
		{
			_OperationsDelegate.Deactivate(etherealizeObjects, waitForCompletion);
		}
		[IdlName("get_state")]
		public override PortableServer.POAManager.State GetState()
		{
			return _OperationsDelegate.GetState();
		}
		[IdlName("get_id")]
		[return: WideChar(false)]
		public override string GetId()
		{
			return _OperationsDelegate.GetId();
		}
	}
}
