/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{
	[IdlName("ServantRetentionPolicyValue")]
	[RepositoryID("IDL:PortableServer/ServantRetentionPolicyValue:1.0")]
	[Helper(typeof(ServantRetentionPolicyValueHelper))]
	public enum ServantRetentionPolicyValue
	{
		[IdlName("RETAIN")]
		RETAIN = 0,
		[IdlName("NON_RETAIN")]
		NON_RETAIN = 1,
	}

}
