/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace TimeBase
{
	public static class IntervalTHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(IntervalTHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(TimeBase.IntervalTHelper.Id(), "IntervalT", new CORBA.StructMember[] {new CORBA.StructMember("lower_bound", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 24), null), new CORBA.StructMember("upper_bound", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 24), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, TimeBase.IntervalT s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static TimeBase.IntervalT Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/TimeBase/IntervalT:1.0";
		}

		public static TimeBase.IntervalT Read(CORBA.IInputStream inputStream)
		{
			var result = new TimeBase.IntervalT();
			result.LowerBound = inputStream.ReadULongLong();
			result.UpperBound = inputStream.ReadULongLong();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, TimeBase.IntervalT s)
		{
			outputStream.WriteULongLong(s.LowerBound);
			outputStream.WriteULongLong(s.UpperBound);
		}

	}
}
