/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace TimeBase
{
	[RepositoryID("IDL:omg.org/TimeBase/IntervalT:1.0")]
	[Helper(typeof(IntervalTHelper))]
	public partial class IntervalT: CORBA.IIDLEntity, IEquatable<TimeBase.IntervalT>
	{
		[IdlName("IntervalT")]
		public ulong LowerBound { get; set; }
		[IdlName("IntervalT")]
		public ulong UpperBound { get; set; }

		public IntervalT()
		{
		}

		public IntervalT(IntervalT other)
		{
			LowerBound = other.LowerBound;
			UpperBound = other.UpperBound;
		}

		public IntervalT(ulong lowerBound, ulong upperBound)
		{
			this.LowerBound = lowerBound;
			this.UpperBound = upperBound;
		}

		public bool Equals(TimeBase.IntervalT? other)
		{
			if (other == null) return false;
			if (!LowerBound.Equals(other.LowerBound)) return false;
			if (!UpperBound.Equals(other.UpperBound)) return false;
			return true;
		}
	}

}
