/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:31
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Dynamic
{
	public static class ParameterHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ParameterHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(Dynamic.ParameterHelper.Id(), "Parameter", new CORBA.StructMember[] {new CORBA.StructMember("argument", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 11), null), new CORBA.StructMember("mode", CORBA.ParameterModeHelper.Type(), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Dynamic.Parameter s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static Dynamic.Parameter Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:Dynamic/Parameter:1.0";
		}

		public static Dynamic.Parameter Read(CORBA.IInputStream inputStream)
		{
			var result = new Dynamic.Parameter();
			result.Argument = inputStream.ReadAny();
			result.Mode = CORBA.ParameterModeHelper.Read(inputStream);
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, Dynamic.Parameter s)
		{
			outputStream.WriteAny(s.Argument);
			CORBA.ParameterModeHelper.Write(outputStream, s.Mode);
		}

	}
}
