/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace DynamicAny
{
		public static class DynSequenceHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(DynSequenceHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateLocalInterfaceTc("IDL:DynamicAny/DynSequence:1.0", "DynSequence");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, DynamicAny.IDynSequence ifz)
			{
				any.InsertObject(ifz);
			}

			public static DynamicAny.IDynSequence Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:DynamicAny/DynSequence:1.0";
			}

			public static DynamicAny.IDynSequence Read(CORBA.IInputStream inputStream)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static void Write(CORBA.IOutputStream outputStream, DynamicAny.IDynSequence ifz)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static DynamicAny.IDynSequence Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is DynamicAny.IDynSequence)
				{
					return (DynamicAny.IDynSequence)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static DynamicAny.IDynSequence UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is DynamicAny.IDynSequence)
				{
					return (DynamicAny.IDynSequence)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}
		}
}
