/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace DynamicAny
{
	public interface IDynFixedOperations : DynamicAny.IDynAnyOperations
	{
		[IdlName("get_value")]
		[return: WideChar(false)]
		public string GetValue();
		[IdlName("set_value")]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.TypeMismatch))]
		[ThrowsIdlException(typeof(DynamicAny.DynAny.InvalidValue))]
		public bool SetValue([WideChar(false)] string val);
	}
}

