/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace DynamicAny
{
	[IdlName("DynSequence")]
	[RepositoryID("IDL:DynamicAny/DynSequence:1.0")]
	[Helper(typeof(DynSequenceHelper))]
	[Stub(typeof(_DynSequenceLocalBase))]
	public interface IDynSequence : CORBA.IIDLEntity, CORBA.ILocalInterface, IDynSequenceOperations, DynamicAny.IDynAny
	{
	}
}

