/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:36
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{
	public interface IPersistentRequestOperations
	{
		[IdlName("reply_available")]
		public bool ReplyAvailable 
		{
			get;
		}
		[IdlName("get_reply")]
		[ThrowsIdlException(typeof(MessageRouting.ReplyNotAvailable))]
		public GIOP.ReplyStatusType12 GetReply(bool blocking, uint timeout, out MessageRouting.MessageBody replyBody);
		[IdlName("associated_handler")]
		public Messaging.IReplyHandler AssociatedHandler 
		{
			get;

			set;
		}
		[IdlName("get_reply_with_context")]
		[ThrowsIdlException(typeof(MessageRouting.ReplyNotAvailable))]
		public GIOP.ReplyStatusType12 GetReplyWithContext(bool blocking, uint timeout, out MessageRouting.MessageBody replyBody, out IOP.ServiceContext[] serviceContexts);
	}
}

