/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{
	public static class LimitedPingHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(LimitedPingHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateValueTc(MessageRouting.LimitedPingHelper.Id(), "LimitedPing", 0, MessageRouting.UnlimitedPingHelper.Type(), new CORBA.ValueMember[] {new CORBA.ValueMember("interval_limit", "IDL:MessageRouting/LimitedPing/interval_limit:1.0", "LimitedPing", "1.0", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 5), null, 1), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, MessageRouting.LimitedPing value)
		{
			any.InsertValue(value);
		}

		public static MessageRouting.LimitedPing Extract(CORBA.Any any)
		{
			try
			{
				return (MessageRouting.LimitedPing) any.ExtractValue();
			}
			catch (InvalidCastException ex)
			{
				throw new CORBA.Marshal(ex.Message);
			}
		}

		public static string Id()
		{
			return "IDL:MessageRouting/LimitedPing:1.0";
		}

		public static MessageRouting.LimitedPing Read(CORBA.IInputStream inputStream)
		{
			return (MessageRouting.LimitedPing) inputStream.ReadValue("IDL:MessageRouting/LimitedPing:1.0");
		}

		public static void Write(CORBA.IOutputStream outputStream, MessageRouting.LimitedPing value)
		{
			outputStream.WriteValue(value, "IDL:MessageRouting/LimitedPing:1.0");
		}

	}
}
