/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ImplementationRepository
{
		public static class AdministrationExtHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(AdministrationExtHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:ImplementationRepository/AdministrationExt:1.0", "AdministrationExt");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, ImplementationRepository.IAdministrationExt ifz)
			{
				any.InsertObject(ifz);
			}

			public static ImplementationRepository.IAdministrationExt Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:ImplementationRepository/AdministrationExt:1.0";
			}

			public static ImplementationRepository.IAdministrationExt Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_AdministrationExtStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, ImplementationRepository.IAdministrationExt ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static ImplementationRepository.IAdministrationExt Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is ImplementationRepository.IAdministrationExt)
				{
					return (ImplementationRepository.IAdministrationExt)obj;
				}
				else if (obj._IsA("IDL:ImplementationRepository/AdministrationExt:1.0"))
				{
					_AdministrationExtStub stub = new _AdministrationExtStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static ImplementationRepository.IAdministrationExt UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is ImplementationRepository.IAdministrationExt)
				{
					return (ImplementationRepository.IAdministrationExt)obj;
				}
				else
				{
					_AdministrationExtStub stub = new _AdministrationExtStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
