/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ImplementationRepository
{
	public static class CannotCompleteHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(CannotCompleteHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateExceptionTc(ImplementationRepository.CannotCompleteHelper.Id(), "CannotComplete", new CORBA.StructMember[] {new CORBA.StructMember("reason", CORBA.ORB.Init().CreateStringTc(0), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, ImplementationRepository.CannotComplete e)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), e);
		}

		public static ImplementationRepository.CannotComplete Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:ImplementationRepository/CannotComplete:1.0";
		}

		public static ImplementationRepository.CannotComplete Read(CORBA.IInputStream inputStream)
		{
			var id = inputStream.ReadString();
			if (!id.Equals(Id()))
			{
				throw new CORBA.Marshal("Wrong id: " + id);
			}
			var result = new ImplementationRepository.CannotComplete();
			result.Reason = inputStream.ReadString();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, ImplementationRepository.CannotComplete e)
		{
			outputStream.WriteString(Id());
			outputStream.WriteString(e.Reason);
		}

	}
}
