/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace ImplementationRepository
{
	[RepositoryID("IDL:ImplementationRepository/EnvironmentVariable:1.0")]
	[Helper(typeof(EnvironmentVariableHelper))]
	public partial class EnvironmentVariable: CORBA.IIDLEntity, IEquatable<ImplementationRepository.EnvironmentVariable>
	{
		[IdlName("EnvironmentVariable")]
		[WideChar(false)]
		public string Name { get; set; }
		[IdlName("EnvironmentVariable")]
		[WideChar(false)]
		public string Value { get; set; }

		public EnvironmentVariable()
		{
		}

		public EnvironmentVariable(EnvironmentVariable other)
		{
			Name = other.Name;
			Value = other.Value;
		}

		public EnvironmentVariable(string name, string value)
		{
			this.Name = name;
			this.Value = value;
		}

		public bool Equals(ImplementationRepository.EnvironmentVariable? other)
		{
			if (other == null) return false;
			if (!Name.Equals(other.Name)) return false;
			if (!Value.Equals(other.Value)) return false;
			return true;
		}
	}

}
