/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ImplementationRepository
{
	public static class ServerActiveStatusHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ServerActiveStatusHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateEnumTc(ImplementationRepository.ServerActiveStatusHelper.Id(),"ServerActiveStatus", new String[] {"ACTIVE_MAYBE", "ACTIVE_YES", "ACTIVE_NO"});
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, ImplementationRepository.ServerActiveStatus value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static ImplementationRepository.ServerActiveStatus Extract(CORBA.Any any)
		{
				var inputStream = any.CreateInputStream();
			try
			{
			return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:ImplementationRepository/ServerActiveStatus:1.0";
		}

		public static ImplementationRepository.ServerActiveStatus Read(CORBA.IInputStream inputStream)
		{
			return (ImplementationRepository.ServerActiveStatus) inputStream.ReadLong();
		}

		public static void Write(CORBA.IOutputStream outputStream, ImplementationRepository.ServerActiveStatus value)
		{
			outputStream.WriteLong((int) value);
		}

	}
}
