/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace GIOP
{
	[IdlName("MsgType_1_1")]
	[RepositoryID("IDL:GIOP/MsgType_1_1:1.0")]
	[Helper(typeof(MsgType11Helper))]
	public enum MsgType11
	{
		[IdlName("Request")]
		Request = 0,
		[IdlName("Reply")]
		Reply = 1,
		[IdlName("CancelRequest")]
		CancelRequest = 2,
		[IdlName("LocateRequest")]
		LocateRequest = 3,
		[IdlName("LocateReply")]
		LocateReply = 4,
		[IdlName("CloseConnection")]
		CloseConnection = 5,
		[IdlName("MessageError")]
		MessageError = 6,
		[IdlName("Fragment")]
		Fragment = 7,
	}

}
