/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace GIOP
{
	public static class RequestReservedHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(RequestReservedHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(GIOP.RequestReservedHelper.Id(), "RequestReserved", CORBA.ORB.Init().CreateArrayTc(3, CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 10)));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, byte[] value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static byte[] Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:GIOP/RequestReserved:1.0";
		}

		public static byte[] Read(CORBA.IInputStream inputStream)
		{
			byte[] result;
			result = new byte[3];
			{
				for (int i0 = 0; i0 < 3; i0++)
				{
					result[i0] = inputStream.ReadOctet();
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, byte[] value)
		{
			if (value.Length < 3)			{
				throw new CORBA.Marshal($"Incorrect array size {value.Length}, expecting 3");
			}
			for (int i0 = 0; i0 < 3; i0++)
			{
				outputStream.WriteOctet(value[i0]);
			}
		}

	}
}
