/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{
	[IdlName("Current")]
	[RepositoryID("IDL:PortableServer/Current:1.0")]
	[Helper(typeof(CurrentHelper))]
	[Stub(typeof(_CurrentLocalBase))]
	public interface ICurrent : CORBA.IIDLEntity, CORBA.ILocalInterface, ICurrentOperations, CORBA.ICurrent
	{
	}
}

