/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace PortableServer
{
	[IdlName("ID_UNIQUENESS_POLICY_ID")]
	public sealed class ID_UNIQUENESS_POLICY_ID
	{
		public const uint Value = 18;
	}
}
