/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{
	public static class POAListHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(POAListHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(PortableServer.POAListHelper.Id(), "POAList", CORBA.ORB.Init().CreateSequenceTc(0, PortableServer.POAHelper.Type()));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, PortableServer.IPOA[] value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static PortableServer.IPOA[] Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:PortableServer/POAList:1.0";
		}

		public static PortableServer.IPOA[] Read(CORBA.IInputStream inputStream)
		{
			PortableServer.IPOA[] result;
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				result = new PortableServer.IPOA[_capacity0];
				for (int i0 = 0; i0 < _capacity0; i0++)
				{
					PortableServer.IPOA _item0;
					_item0 = PortableServer.POAHelper.Read(inputStream);
					result[i0] = _item0;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, PortableServer.IPOA[] value)
		{
			{
				outputStream.WriteLong(value.Length);
				for (int i0 = 0; i0 < value.Length; i0++)
				{
					PortableServer.POAHelper.Write(outputStream, value[i0]);
				}
			}
		}

	}
}
