/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableServer
{
	public static class ThreadPolicyValueHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ThreadPolicyValueHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateEnumTc(PortableServer.ThreadPolicyValueHelper.Id(),"ThreadPolicyValue", new String[] {"ORB_CTRL_MODEL", "SINGLE_THREAD_MODEL", "MAIN_THREAD_MODEL"});
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, PortableServer.ThreadPolicyValue value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static PortableServer.ThreadPolicyValue Extract(CORBA.Any any)
		{
				var inputStream = any.CreateInputStream();
			try
			{
			return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:PortableServer/ThreadPolicyValue:1.0";
		}

		public static PortableServer.ThreadPolicyValue Read(CORBA.IInputStream inputStream)
		{
			return (PortableServer.ThreadPolicyValue) inputStream.ReadLong();
		}

		public static void Write(CORBA.IOutputStream outputStream, PortableServer.ThreadPolicyValue value)
		{
			outputStream.WriteLong((int) value);
		}

	}
}
