/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:34
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Messaging
{
	public static class PolicyValueSeqHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(PolicyValueSeqHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(Messaging.PolicyValueSeqHelper.Id(), "PolicyValueSeq", CORBA.ORB.Init().CreateSequenceTc(0, Messaging.PolicyValueHelper.Type()));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Messaging.PolicyValue[] value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static Messaging.PolicyValue[] Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:Messaging/PolicyValueSeq:1.0";
		}

		public static Messaging.PolicyValue[] Read(CORBA.IInputStream inputStream)
		{
			Messaging.PolicyValue[] result;
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				result = new Messaging.PolicyValue[_capacity0];
				for (int i0 = 0; i0 < _capacity0; i0++)
				{
					Messaging.PolicyValue _item0;
					_item0 = Messaging.PolicyValueHelper.Read(inputStream);
					result[i0] = _item0;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, Messaging.PolicyValue[] value)
		{
			{
				outputStream.WriteLong(value.Length);
				for (int i0 = 0; i0 < value.Length; i0++)
				{
					Messaging.PolicyValueHelper.Write(outputStream, value[i0]);
				}
			}
		}

	}
}
