/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:33
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Messaging
{
		public static class ReplyEndTimePolicyHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(ReplyEndTimePolicyHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateLocalInterfaceTc("IDL:Messaging/ReplyEndTimePolicy:1.0", "ReplyEndTimePolicy");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, Messaging.IReplyEndTimePolicy ifz)
			{
				any.InsertObject(ifz);
			}

			public static Messaging.IReplyEndTimePolicy Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:Messaging/ReplyEndTimePolicy:1.0";
			}

			public static Messaging.IReplyEndTimePolicy Read(CORBA.IInputStream inputStream)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static void Write(CORBA.IOutputStream outputStream, Messaging.IReplyEndTimePolicy ifz)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static Messaging.IReplyEndTimePolicy Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is Messaging.IReplyEndTimePolicy)
				{
					return (Messaging.IReplyEndTimePolicy)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static Messaging.IReplyEndTimePolicy UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is Messaging.IReplyEndTimePolicy)
				{
					return (Messaging.IReplyEndTimePolicy)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}
		}
}
