/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:31
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace Messaging
{
	[IdlName("ROUTE_FORWARD")]
	public sealed class ROUTE_FORWARD
	{
		public const short Value = 1;
	}
}
