/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ETF
{
	public abstract class _FactoriesLocalBase: CORBA.LocalObject, IFactories
	{
		private string[] _ids = {"IDL:omg.org/ETF/Factories:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("create_connection")]
		public abstract ETF.IConnection CreateConnection(RTCORBA.IProtocolProperties props);
		[IdlName("create_listener")]
		public abstract ETF.IListener CreateListener(RTCORBA.IProtocolProperties props, uint stacksize, short basePriority);
		[IdlName("demarshal_profile")]
		public abstract ETF.IProfile DemarshalProfile(ref IOP.TaggedProfile taggedProfile, out IOP.TaggedComponent[] components);
		[IdlName("decode_corbaloc")]
		public abstract ETF.IProfile DecodeCorbaloc([WideChar(false)] string corbaloc);
		[IdlName("profile_tag")]
		public abstract uint ProfileTag 
		{
			get;
		}
	}

}
