/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ETF
{
	public abstract class _ListenerLocalBase: CORBA.LocalObject, IListener
	{
		private string[] _ids = {"IDL:omg.org/ETF/Listener:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("set_handle")]
		public abstract void SetHandle(ETF.IHandle up);
		[IdlName("accept")]
		public abstract ETF.IConnection Accept();
		[IdlName("listen")]
		public abstract void Listen();
		[IdlName("destroy")]
		public abstract void Destroy();
		[IdlName("completed_data")]
		public abstract void CompletedData(ETF.IConnection conn);
		[IdlName("endpoint")]
		public abstract ETF.IProfile Endpoint 
		{
			get;
		}
	}

}
