/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ETF
{
	public interface IBufferListOperations
	{
		[IdlName("add_buffer")]
		public uint AddBuffer(uint size, ref byte[] buf);
		[IdlName("num_buffers")]
		public uint NumBuffers 
		{
			get;
		}
		[IdlName("get_buffer")]
		public void GetBuffer(uint index, ref byte[] buf);
		[IdlName("release_buffers")]
		public void ReleaseBuffers();
	}
}

