/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ETF
{

	public class ProfileLocalTie: _ProfileLocalBase
	{
		public IProfileOperations _OperationsDelegate { get; set; }

		public ProfileLocalTie(IProfileOperations d)
		{
			_OperationsDelegate = d;
		}

		[IdlName("marshal")]
		public override void Marshal(ref IOP.TaggedProfile taggedProfile, ref IOP.TaggedComponent[] components)
		{
			_OperationsDelegate.Marshal(ref taggedProfile, ref components);
		}
		[IdlName("hash")]
		public override uint Hash()
		{
			return _OperationsDelegate.Hash();
		}
		[IdlName("copy")]
		public override ETF.IProfile Copy()
		{
			return _OperationsDelegate.Copy();
		}
		[IdlName("is_match")]
		public override bool IsMatch(ETF.IProfile prof)
		{
			return _OperationsDelegate.IsMatch(prof);
		}
		public override GIOP.Version Version 
		{
			get
			{
				return _OperationsDelegate.Version;
			}
		}
		[IdlName("set_object_key")]
		public override void SetObjectKey(byte[] key)
		{
			_OperationsDelegate.SetObjectKey(key);
		}
		[IdlName("get_object_key")]
		public override byte[] GetObjectKey()
		{
			return _OperationsDelegate.GetObjectKey();
		}
		public override int Tag 
		{
			get
			{
				return _OperationsDelegate.Tag;
			}
		}
	}
}
