/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableInterceptor
{
	public abstract class _PolicyFactoryLocalBase: CORBA.LocalObject, IPolicyFactory
	{
		private string[] _ids = {"IDL:PortableInterceptor/PolicyFactory:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("create_policy")]
		[ThrowsIdlException(typeof(CORBA.PolicyError))]
		public abstract CORBA.IPolicy CreatePolicy(uint type, CORBA.Any value);
	}

}
