/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableInterceptor
{
	[IdlName("Interceptor")]
	[RepositoryID("IDL:PortableInterceptor/Interceptor:1.0")]
	[Helper(typeof(InterceptorHelper))]
	[Stub(typeof(_InterceptorLocalBase))]
	public interface IInterceptor : CORBA.IIDLEntity, CORBA.ILocalInterface, IInterceptorOperations
	{
	}
}

