/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 26/02/2024 12:18:44
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Chat
{

	public class ClientPOATie: ClientPOA
	{
		public IClientOperations _OperationsDelegate { get; set; }
		private PortableServer.IPOA _poa;

		public ClientPOATie(IClientOperations d)
		{
			_OperationsDelegate = d;
		}

		public ClientPOATie(IClientOperations d, PortableServer.POA poa)
		{
			_OperationsDelegate = d;
			_poa = poa;
		}

		public override PortableServer.IPOA _DefaultPOA()
		{
			if (_poa != null)
			{
				return _poa;
			}
			return base._DefaultPOA();
		}

		public override Chat.IClient _This()
		{
			return Chat.ClientHelper.Narrow(_ThisObject());
		}

		public override Chat.IClient _This(CORBA.ORB orb)
		{
			return Chat.ClientHelper.Narrow(_ThisObject(orb));
		}

		[WideChar(false)]
		public override string Name 
		{
			get
			{
				return _OperationsDelegate.Name;
			}
		}
		[IdlName("SendMessage")]
		public override void SendMessage(Chat.Message msg)
		{
			_OperationsDelegate.SendMessage(msg);
		}
	}
}
