/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:30
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MIOP
{
	public static class UipmcProfileBodyHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(UipmcProfileBodyHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(MIOP.UipmcProfileBodyHelper.Id(), "UIPMC_ProfileBody", new CORBA.StructMember[] {new CORBA.StructMember("miop_version", GIOP.VersionHelper.Type(), null), new CORBA.StructMember("the_address", CORBA.ORB.Init().CreateStringTc(0), null), new CORBA.StructMember("the_port", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 4), null), new CORBA.StructMember("components", CORBA.ORB.Init().CreateSequenceTc(0, IOP.TaggedComponentHelper.Type()), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, MIOP.UipmcProfileBody s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static MIOP.UipmcProfileBody Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/MIOP/UIPMC_ProfileBody:1.0";
		}

		public static MIOP.UipmcProfileBody Read(CORBA.IInputStream inputStream)
		{
			var result = new MIOP.UipmcProfileBody();
			result.MiopVersion = GIOP.VersionHelper.Read(inputStream);
			result.TheAddress = inputStream.ReadString();
			result.ThePort = inputStream.ReadShort();
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				result.Components = new IOP.TaggedComponent[_capacity0];
				for (int i0 = 0; i0 < _capacity0; i0++)
				{
					IOP.TaggedComponent _item0;
					_item0 = IOP.TaggedComponentHelper.Read(inputStream);
					result.Components[i0] = _item0;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, MIOP.UipmcProfileBody s)
		{
			GIOP.VersionHelper.Write(outputStream, s.MiopVersion);
			outputStream.WriteString(s.TheAddress);
			outputStream.WriteShort(s.ThePort);
			{
				outputStream.WriteLong(s.Components.Length);
				for (int i0 = 0; i0 < s.Components.Length; i0++)
				{
					IOP.TaggedComponentHelper.Write(outputStream, s.Components[i0]);
				}
			}
		}

	}
}
