/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace IIOP
{
	public static class ListenPointHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ListenPointHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(IIOP.ListenPointHelper.Id(), "ListenPoint", new CORBA.StructMember[] {new CORBA.StructMember("host", CORBA.ORB.Init().CreateStringTc(0), null), new CORBA.StructMember("port", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 2), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, IIOP.ListenPoint s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static IIOP.ListenPoint Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:IIOP/ListenPoint:1.0";
		}

		public static IIOP.ListenPoint Read(CORBA.IInputStream inputStream)
		{
			var result = new IIOP.ListenPoint();
			result.Host = inputStream.ReadString();
			result.Port = inputStream.ReadUShort();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, IIOP.ListenPoint s)
		{
			outputStream.WriteString(s.Host);
			outputStream.WriteUShort(s.Port);
		}

	}
}
