/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace Compression
{
	[IdlName("COMPRESSORID_XAR")]
	public sealed class COMPRESSORID_XAR
	{
		public const ushort Value = 9;
	}
}
