/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:38
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ImplementationRepository
{
	[IdlName("AdministrationExt")]
	[RepositoryID("IDL:ImplementationRepository/AdministrationExt:1.0")]
	[Helper(typeof(AdministrationExtHelper))]
	[Stub(typeof(_AdministrationExtStub))]
	public interface IAdministrationExt : CORBA.IIDLEntity, CORBA.IObject, IAdministrationExtOperations, ImplementationRepository.IAdministration
	{
	}
}

