/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableInterceptor
{
	public abstract class _ORBInitializerLocalBase: CORBA.LocalObject, IORBInitializer
	{
		private string[] _ids = {"IDL:PortableInterceptor/ORBInitializer:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("pre_init")]
		public abstract void PreInit(PortableInterceptor.IORBInitInfo info);
		[IdlName("post_init")]
		public abstract void PostInit(PortableInterceptor.IORBInitInfo info);
	}

}
