/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableInterceptor
{
		public static class ClientRequestInterceptorHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(ClientRequestInterceptorHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateLocalInterfaceTc("IDL:PortableInterceptor/ClientRequestInterceptor:1.0", "ClientRequestInterceptor");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, PortableInterceptor.IClientRequestInterceptor ifz)
			{
				any.InsertObject(ifz);
			}

			public static PortableInterceptor.IClientRequestInterceptor Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:PortableInterceptor/ClientRequestInterceptor:1.0";
			}

			public static PortableInterceptor.IClientRequestInterceptor Read(CORBA.IInputStream inputStream)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static void Write(CORBA.IOutputStream outputStream, PortableInterceptor.IClientRequestInterceptor ifz)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static PortableInterceptor.IClientRequestInterceptor Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is PortableInterceptor.IClientRequestInterceptor)
				{
					return (PortableInterceptor.IClientRequestInterceptor)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static PortableInterceptor.IClientRequestInterceptor UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is PortableInterceptor.IClientRequestInterceptor)
				{
					return (PortableInterceptor.IClientRequestInterceptor)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}
		}
}
