/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableInterceptor
{
		public static class CurrentHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(CurrentHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateLocalInterfaceTc("IDL:PortableInterceptor/Current:1.0", "Current");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, PortableInterceptor.ICurrent ifz)
			{
				any.InsertObject(ifz);
			}

			public static PortableInterceptor.ICurrent Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:PortableInterceptor/Current:1.0";
			}

			public static PortableInterceptor.ICurrent Read(CORBA.IInputStream inputStream)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static void Write(CORBA.IOutputStream outputStream, PortableInterceptor.ICurrent ifz)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static PortableInterceptor.ICurrent Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is PortableInterceptor.ICurrent)
				{
					return (PortableInterceptor.ICurrent)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static PortableInterceptor.ICurrent UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is PortableInterceptor.ICurrent)
				{
					return (PortableInterceptor.ICurrent)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}
		}
}
