/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableInterceptor
{
	[RepositoryID("IDL:PortableInterceptor/ObjectReferenceTemplate:1.0")]
	[Helper(typeof(ObjectReferenceTemplateHelper))]
	public interface IObjectReferenceTemplate : CORBA.IValueBase, PortableInterceptor.IObjectReferenceFactory
	{
		[IdlName("server_id")]
		[WideChar(false)]
		public string ServerId 
		{
			get;
		}
		[IdlName("orb_id")]
		[WideChar(false)]
		public string OrbId 
		{
			get;
		}
		[IdlName("adapter_name")]
		public string[] AdapterName 
		{
			get;
		}
	}
}

