/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CSIIOP
{
	public static class CompoundSecMechHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(CompoundSecMechHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(CSIIOP.CompoundSecMechHelper.Id(), "CompoundSecMech", new CORBA.StructMember[] {new CORBA.StructMember("target_requires", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 2), null), new CORBA.StructMember("transport_mech", IOP.TaggedComponentHelper.Type(), null), new CORBA.StructMember("as_context_mech", CSIIOP.AsContextSecHelper.Type(), null), new CORBA.StructMember("sas_context_mech", CSIIOP.SasContextSecHelper.Type(), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, CSIIOP.CompoundSecMech s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static CSIIOP.CompoundSecMech Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:CSIIOP/CompoundSecMech:1.0";
		}

		public static CSIIOP.CompoundSecMech Read(CORBA.IInputStream inputStream)
		{
			var result = new CSIIOP.CompoundSecMech();
			result.TargetRequires = inputStream.ReadUShort();
			result.TransportMech = IOP.TaggedComponentHelper.Read(inputStream);
			result.AsContextMech = CSIIOP.AsContextSecHelper.Read(inputStream);
			result.SasContextMech = CSIIOP.SasContextSecHelper.Read(inputStream);
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, CSIIOP.CompoundSecMech s)
		{
			outputStream.WriteUShort(s.TargetRequires);
			IOP.TaggedComponentHelper.Write(outputStream, s.TransportMech);
			CSIIOP.AsContextSecHelper.Write(outputStream, s.AsContextMech);
			CSIIOP.SasContextSecHelper.Write(outputStream, s.SasContextMech);
		}

	}
}
