/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace DotNetOrb.ImR
{
	public static class ServerInfoSeqHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ServerInfoSeqHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(DotNetOrb.ImR.ServerInfoSeqHelper.Id(), "ServerInfoSeq", CORBA.ORB.Init().CreateSequenceTc(0, DotNetOrb.ImR.ServerInfoHelper.Type()));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, DotNetOrb.ImR.ServerInfo[] value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static DotNetOrb.ImR.ServerInfo[] Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:DotNetOrb/ImR/ServerInfoSeq:1.0";
		}

		public static DotNetOrb.ImR.ServerInfo[] Read(CORBA.IInputStream inputStream)
		{
			DotNetOrb.ImR.ServerInfo[] result;
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				result = new DotNetOrb.ImR.ServerInfo[_capacity0];
				for (int i0 = 0; i0 < _capacity0; i0++)
				{
					DotNetOrb.ImR.ServerInfo _item0;
					_item0 = DotNetOrb.ImR.ServerInfoHelper.Read(inputStream);
					result[i0] = _item0;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, DotNetOrb.ImR.ServerInfo[] value)
		{
			{
				outputStream.WriteLong(value.Length);
				for (int i0 = 0; i0 < value.Length; i0++)
				{
					DotNetOrb.ImR.ServerInfoHelper.Write(outputStream, value[i0]);
				}
			}
		}

	}
}
