/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:30
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace PortableGroup
{
	public interface IGOAOperations : PortableServer.IPOAOperations
	{
		[IdlName("create_id_for_reference")]
		[ThrowsIdlException(typeof(PortableGroup.GOA.NotAGroupObject))]
		public byte[] CreateIdForReference(CORBA.IObject theRef);
		[IdlName("reference_to_ids")]
		[ThrowsIdlException(typeof(PortableGroup.GOA.NotAGroupObject))]
		public byte[][] ReferenceToIds(CORBA.IObject theRef);
		[IdlName("associate_reference_with_id")]
		[ThrowsIdlException(typeof(PortableGroup.GOA.NotAGroupObject))]
		public void AssociateReferenceWithId(CORBA.IObject @ref, byte[] oid);
		[IdlName("disassociate_reference_with_id")]
		[ThrowsIdlException(typeof(PortableGroup.GOA.NotAGroupObject))]
		public void DisassociateReferenceWithId(CORBA.IObject @ref, byte[] oid);
	}
}

