/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CSI
{
	[IdlName("GSS_NT_Export_Name_OID")]
	public sealed class GssNtExportNameOid
	{
		public const string Value = "oid:1.3.6.1.5.6.4";
	}
}
