/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CSI
{
	public static class SASContextBodyHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(SASContextBodyHelper))
				{
					if (type == null)
					{
						var members = new List<CORBA.UnionMember>();
						CORBA.Any anyLabel;
						anyLabel = CORBA.ORB.Init().CreateAny();
						anyLabel.InsertShort(0);
						members.Add(new CORBA.UnionMember("establish_msg", anyLabel, CSI.EstablishContextHelper.Type(), null));
						type = CORBA.ORB.Init().CreateUnionTc(CSI.SASContextBodyHelper.Id(), "SASContextBody", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 4), members.ToArray());
						anyLabel = CORBA.ORB.Init().CreateAny();
						anyLabel.InsertShort(1);
						members.Add(new CORBA.UnionMember("complete_msg", anyLabel, CSI.CompleteEstablishContextHelper.Type(), null));
						type = CORBA.ORB.Init().CreateUnionTc(CSI.SASContextBodyHelper.Id(), "SASContextBody", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 4), members.ToArray());
						anyLabel = CORBA.ORB.Init().CreateAny();
						anyLabel.InsertShort(4);
						members.Add(new CORBA.UnionMember("error_msg", anyLabel, CSI.ContextErrorHelper.Type(), null));
						type = CORBA.ORB.Init().CreateUnionTc(CSI.SASContextBodyHelper.Id(), "SASContextBody", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 4), members.ToArray());
						anyLabel = CORBA.ORB.Init().CreateAny();
						anyLabel.InsertShort(5);
						members.Add(new CORBA.UnionMember("in_context_msg", anyLabel, CSI.MessageInContextHelper.Type(), null));
						type = CORBA.ORB.Init().CreateUnionTc(CSI.SASContextBodyHelper.Id(), "SASContextBody", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 4), members.ToArray());
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, CSI.SASContextBody value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static CSI.SASContextBody Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
		    return "IDL:CSI/SASContextBody:1.0";
		}

		public static CSI.SASContextBody Read(CORBA.IInputStream inputStream)
		{
			var result = new CSI.SASContextBody();
			short disc;
			disc = inputStream.ReadShort();
			switch (disc)
			{
				case 0:
				{
					result.EstablishMsg = CSI.EstablishContextHelper.Read(inputStream);
					break;
				}
				case 1:
				{
					result.CompleteMsg = CSI.CompleteEstablishContextHelper.Read(inputStream);
					break;
				}
				case 4:
				{
					result.ErrorMsg = CSI.ContextErrorHelper.Read(inputStream);
					break;
				}
				case 5:
				{
					result.InContextMsg = CSI.MessageInContextHelper.Read(inputStream);
					break;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, CSI.SASContextBody value)
		{
			outputStream.WriteShort(value._Discriminator);
			switch (value._Discriminator)
			{
				case 0:
				{
					CSI.EstablishContextHelper.Write(outputStream, value.EstablishMsg);
					break;
				}
				case 1:
				{
					CSI.CompleteEstablishContextHelper.Write(outputStream, value.CompleteMsg);
					break;
				}
				case 4:
				{
					CSI.ContextErrorHelper.Write(outputStream, value.ErrorMsg);
					break;
				}
				case 5:
				{
					CSI.MessageInContextHelper.Write(outputStream, value.InContextMsg);
					break;
				}
			}
		}

	}
}
