/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:32:22
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace IOP
{
	[IdlName("ChainBypassInfo")]
	public sealed class ChainBypassInfo
	{
		public const uint Value = 3;
	}
}
