/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:32:22
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace IOP
{
	public static class EncodingFormatHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(EncodingFormatHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(IOP.EncodingFormatHelper.Id(), "EncodingFormat", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 2));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, short value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static short Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:IOP/EncodingFormat:1.0";
		}

		public static short Read(CORBA.IInputStream inputStream)
		{
			short result;
			result = inputStream.ReadShort();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, short value)
		{
			outputStream.WriteShort(value);
		}

	}
}
