/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace IOP
{
	public static class EndpointIdPositionComponentHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(EndpointIdPositionComponentHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(IOP.EndpointIdPositionComponentHelper.Id(), "EndpointIdPositionComponent", new CORBA.StructMember[] {new CORBA.StructMember("begin", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 2), null), new CORBA.StructMember("end", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 2), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, IOP.EndpointIdPositionComponent s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static IOP.EndpointIdPositionComponent Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:IOP/EndpointIdPositionComponent:1.0";
		}

		public static IOP.EndpointIdPositionComponent Read(CORBA.IInputStream inputStream)
		{
			var result = new IOP.EndpointIdPositionComponent();
			result.Begin = inputStream.ReadUShort();
			result.End = inputStream.ReadUShort();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, IOP.EndpointIdPositionComponent s)
		{
			outputStream.WriteUShort(s.Begin);
			outputStream.WriteUShort(s.End);
		}

	}
}
