/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace IOP
{
	[IdlName("TAG_CODE_SETS")]
	public sealed class TAG_CODE_SETS
	{
		public const uint Value = 1;
	}
}
