/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace IOP
{
	[IdlName("TAG_JAVA_CODEBASE")]
	public sealed class TAG_JAVA_CODEBASE
	{
		public const uint Value = 25;
	}
}
