/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace IOP
{
	[IdlName("TAG_CSI_ECMA_Secret_SEC_MECH")]
	public sealed class TagCsiEcmaSecretSecMech
	{
		public const uint Value = 18;
	}
}
