/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:36
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{
	[IdlName("PersistentRequestRouter")]
	[RepositoryID("IDL:MessageRouting/PersistentRequestRouter:1.0")]
	[Helper(typeof(PersistentRequestRouterHelper))]
	[Stub(typeof(_PersistentRequestRouterStub))]
	public interface IPersistentRequestRouter : CORBA.IIDLEntity, CORBA.IObject, IPersistentRequestRouterOperations
	{
	}
}

