/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:35
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{
	public interface IRouterOperations
	{
		[IdlName("send_request")]
		public void SendRequest(MessageRouting.RequestInfo req);
		[IdlName("send_multiple_requests")]
		public void SendMultipleRequests(MessageRouting.RequestInfo[] reqSeq);
		[IdlName("admin")]
		public MessageRouting.IRouterAdmin Admin 
		{
			get;
		}
	}
}

