/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:36
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{
	public static class ReplyNotAvailableHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ReplyNotAvailableHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateExceptionTc(MessageRouting.ReplyNotAvailableHelper.Id(), "ReplyNotAvailable", new CORBA.StructMember[] {});
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, MessageRouting.ReplyNotAvailable e)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), e);
		}

		public static MessageRouting.ReplyNotAvailable Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:MessageRouting/ReplyNotAvailable:1.0";
		}

		public static MessageRouting.ReplyNotAvailable Read(CORBA.IInputStream inputStream)
		{
			var id = inputStream.ReadString();
			if (!id.Equals(Id()))
			{
				throw new CORBA.Marshal("Wrong id: " + id);
			}
			var result = new MessageRouting.ReplyNotAvailable();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, MessageRouting.ReplyNotAvailable e)
		{
			outputStream.WriteString(Id());
		}

	}
}
