/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:35
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{

	public class RouterPOATie: RouterPOA
	{
		public IRouterOperations _OperationsDelegate { get; set; }
		private PortableServer.IPOA _poa;

		public RouterPOATie(IRouterOperations d)
		{
			_OperationsDelegate = d;
		}

		public RouterPOATie(IRouterOperations d, PortableServer.POA poa)
		{
			_OperationsDelegate = d;
			_poa = poa;
		}

		public override PortableServer.IPOA _DefaultPOA()
		{
			if (_poa != null)
			{
				return _poa;
			}
			return base._DefaultPOA();
		}

		public override MessageRouting.IRouter _This()
		{
			return MessageRouting.RouterHelper.Narrow(_ThisObject());
		}

		public override MessageRouting.IRouter _This(CORBA.ORB orb)
		{
			return MessageRouting.RouterHelper.Narrow(_ThisObject(orb));
		}

		[IdlName("send_request")]
		public override void SendRequest(MessageRouting.RequestInfo req)
		{
			_OperationsDelegate.SendRequest(req);
		}
		[IdlName("send_multiple_requests")]
		public override void SendMultipleRequests(MessageRouting.RequestInfo[] reqSeq)
		{
			_OperationsDelegate.SendMultipleRequests(reqSeq);
		}
		public override MessageRouting.IRouterAdmin Admin 
		{
			get
			{
				return _OperationsDelegate.Admin;
			}
		}
	}
}
