/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:36
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace MessageRouting
{

	public class UntypedReplyHandlerPOATie: UntypedReplyHandlerPOA
	{
		public IUntypedReplyHandlerOperations _OperationsDelegate { get; set; }
		private PortableServer.IPOA _poa;

		public UntypedReplyHandlerPOATie(IUntypedReplyHandlerOperations d)
		{
			_OperationsDelegate = d;
		}

		public UntypedReplyHandlerPOATie(IUntypedReplyHandlerOperations d, PortableServer.POA poa)
		{
			_OperationsDelegate = d;
			_poa = poa;
		}

		public override PortableServer.IPOA _DefaultPOA()
		{
			if (_poa != null)
			{
				return _poa;
			}
			return base._DefaultPOA();
		}

		public override MessageRouting.IUntypedReplyHandler _This()
		{
			return MessageRouting.UntypedReplyHandlerHelper.Narrow(_ThisObject());
		}

		public override MessageRouting.IUntypedReplyHandler _This(CORBA.ORB orb)
		{
			return MessageRouting.UntypedReplyHandlerHelper.Narrow(_ThisObject(orb));
		}

		[IdlName("reply")]
		public override void Reply([WideChar(false)] string operationName, GIOP.ReplyStatusType12 replyType, MessageRouting.MessageBody replyBody)
		{
			_OperationsDelegate.Reply(operationName, replyType, replyBody);
		}
	}
}
