/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace BiDirPolicy
{
	[IdlName("BidirectionalPolicy")]
	[RepositoryID("IDL:omg.org/BiDirPolicy/BidirectionalPolicy:1.0")]
	[Helper(typeof(BidirectionalPolicyHelper))]
	[Stub(typeof(_BidirectionalPolicyStub))]
	public interface IBidirectionalPolicy : CORBA.IIDLEntity, CORBA.IObject, IBidirectionalPolicyOperations, CORBA.IPolicy
	{
	}
}

