/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 27/08/2025 6:53:30
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Test.VT
{
	public interface IEmployeeRecordValueFactory : CORBA.IValueFactory
	{
		[IdlName("init")]
		EmployeeRecord Init([WideChar(false)] string name, [WideChar(false)] string ssn);
	}
}

