/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CSIIOP
{
	[IdlName("EstablishTrustInTarget")]
	public sealed class EstablishTrustInTarget
	{
		public const ushort Value = 32;
	}
}
