/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RTCORBA
{
	public abstract class _ServerProtocolPolicyLocalBase: CORBA.LocalObject, IServerProtocolPolicy
	{
		private string[] _ids = {"IDL:RTCORBA/ServerProtocolPolicy:1.0","IDL:CORBA/Policy:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("policy_type")]
		public abstract uint PolicyType 
		{
			get;
		}
		[IdlName("copy")]
		public abstract CORBA.IPolicy Copy();
		[IdlName("destroy")]
		public abstract void Destroy();
		[IdlName("protocols")]
		public abstract RTCORBA.Protocol[] Protocols 
		{
			get;
		}
	}

}
