/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RTCORBA
{

	public class MutexLocalTie: _MutexLocalBase
	{
		public IMutexOperations _OperationsDelegate { get; set; }

		public MutexLocalTie(IMutexOperations d)
		{
			_OperationsDelegate = d;
		}

		[IdlName("lock")]
		public override void Lock()
		{
			_OperationsDelegate.Lock();
		}
		[IdlName("unlock")]
		public override void Unlock()
		{
			_OperationsDelegate.Unlock();
		}
		[IdlName("try_lock")]
		public override bool TryLock(ulong maxWait)
		{
			return _OperationsDelegate.TryLock(maxWait);
		}
	}
}
