/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RTCORBA
{
		public static class PrivateConnectionPolicyHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(PrivateConnectionPolicyHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateLocalInterfaceTc("IDL:RTCORBA/PrivateConnectionPolicy:1.0", "PrivateConnectionPolicy");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, RTCORBA.IPrivateConnectionPolicy ifz)
			{
				any.InsertObject(ifz);
			}

			public static RTCORBA.IPrivateConnectionPolicy Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:RTCORBA/PrivateConnectionPolicy:1.0";
			}

			public static RTCORBA.IPrivateConnectionPolicy Read(CORBA.IInputStream inputStream)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static void Write(CORBA.IOutputStream outputStream, RTCORBA.IPrivateConnectionPolicy ifz)
			{
				throw new CORBA.Marshal("Local interface");
			}

			public static RTCORBA.IPrivateConnectionPolicy Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is RTCORBA.IPrivateConnectionPolicy)
				{
					return (RTCORBA.IPrivateConnectionPolicy)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static RTCORBA.IPrivateConnectionPolicy UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is RTCORBA.IPrivateConnectionPolicy)
				{
					return (RTCORBA.IPrivateConnectionPolicy)obj;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}
		}
}
