/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace DotNetOrb.ImR
{
		public static class ServerStartupDaemonHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(ServerStartupDaemonHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:DotNetOrb/ImR/ServerStartupDaemon:1.0", "ServerStartupDaemon");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, DotNetOrb.ImR.IServerStartupDaemon ifz)
			{
				any.InsertObject(ifz);
			}

			public static DotNetOrb.ImR.IServerStartupDaemon Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:DotNetOrb/ImR/ServerStartupDaemon:1.0";
			}

			public static DotNetOrb.ImR.IServerStartupDaemon Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_ServerStartupDaemonStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, DotNetOrb.ImR.IServerStartupDaemon ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static DotNetOrb.ImR.IServerStartupDaemon Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is DotNetOrb.ImR.IServerStartupDaemon)
				{
					return (DotNetOrb.ImR.IServerStartupDaemon)obj;
				}
				else if (obj._IsA("IDL:DotNetOrb/ImR/ServerStartupDaemon:1.0"))
				{
					_ServerStartupDaemonStub stub = new _ServerStartupDaemonStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static DotNetOrb.ImR.IServerStartupDaemon UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is DotNetOrb.ImR.IServerStartupDaemon)
				{
					return (DotNetOrb.ImR.IServerStartupDaemon)obj;
				}
				else
				{
					_ServerStartupDaemonStub stub = new _ServerStartupDaemonStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
