/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
		public static class AttributeDefHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(AttributeDefHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:CORBA/AttributeDef:1.0", "AttributeDef");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, CORBA.IAttributeDef ifz)
			{
				any.InsertObject(ifz);
			}

			public static CORBA.IAttributeDef Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:CORBA/AttributeDef:1.0";
			}

			public static CORBA.IAttributeDef Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_AttributeDefStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, CORBA.IAttributeDef ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static CORBA.IAttributeDef Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IAttributeDef)
				{
					return (CORBA.IAttributeDef)obj;
				}
				else if (obj._IsA("IDL:CORBA/AttributeDef:1.0"))
				{
					_AttributeDefStub stub = new _AttributeDefStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static CORBA.IAttributeDef UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IAttributeDef)
				{
					return (CORBA.IAttributeDef)obj;
				}
				else
				{
					_AttributeDefStub stub = new _AttributeDefStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
