/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
		public static class FixedDefHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(FixedDefHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:CORBA/FixedDef:1.0", "FixedDef");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, CORBA.IFixedDef ifz)
			{
				any.InsertObject(ifz);
			}

			public static CORBA.IFixedDef Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:CORBA/FixedDef:1.0";
			}

			public static CORBA.IFixedDef Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_FixedDefStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, CORBA.IFixedDef ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static CORBA.IFixedDef Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IFixedDef)
				{
					return (CORBA.IFixedDef)obj;
				}
				else if (obj._IsA("IDL:CORBA/FixedDef:1.0"))
				{
					_FixedDefStub stub = new _FixedDefStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static CORBA.IFixedDef UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IFixedDef)
				{
					return (CORBA.IFixedDef)obj;
				}
				else
				{
					_FixedDefStub stub = new _FixedDefStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
