/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:32:22
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("Container")]
	[RepositoryID("IDL:CORBA/Container:1.0")]
	[Helper(typeof(ContainerHelper))]
	[Stub(typeof(_ContainerStub))]
	public interface IContainer : CORBA.IIDLEntity, CORBA.IObject, IContainerOperations, CORBA.IIRObject
	{
	}
}

