/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
		public static class IDLTypeHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(IDLTypeHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:CORBA/IDLType:1.0", "IDLType");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, CORBA.IIDLType ifz)
			{
				any.InsertObject(ifz);
			}

			public static CORBA.IIDLType Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:CORBA/IDLType:1.0";
			}

			public static CORBA.IIDLType Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_IDLTypeStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, CORBA.IIDLType ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static CORBA.IIDLType Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IIDLType)
				{
					return (CORBA.IIDLType)obj;
				}
				else if (obj._IsA("IDL:CORBA/IDLType:1.0"))
				{
					_IDLTypeStub stub = new _IDLTypeStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static CORBA.IIDLType UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IIDLType)
				{
					return (CORBA.IIDLType)obj;
				}
				else
				{
					_IDLTypeStub stub = new _IDLTypeStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
