/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:32:21
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("DomainManager")]
	[RepositoryID("IDL:CORBA/DomainManager:1.0")]
	[Helper(typeof(DomainManagerHelper))]
	[Stub(typeof(_DomainManagerStub))]
	public interface IDomainManager : CORBA.IIDLEntity, CORBA.IObject, IDomainManagerOperations
	{
	}
}

