/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:26
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("DomainManager")]
	[RepositoryID("IDL:CORBA/DomainManager:1.0")]
	[Helper(typeof(DomainManagerHelper))]
	[Stub(typeof(_DomainManagerStub))]
	public interface IDomainManager : CORBA.IIDLEntity, CORBA.IObject, IDomainManagerOperations
	{
	}
}

