/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("EnumDef")]
	[RepositoryID("IDL:CORBA/EnumDef:1.0")]
	[Helper(typeof(EnumDefHelper))]
	[Stub(typeof(_EnumDefStub))]
	public interface IEnumDef : CORBA.IIDLEntity, CORBA.IObject, IEnumDefOperations, CORBA.ITypedefDef
	{
	}
}

