/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:32:22
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	public interface IExtValueDefOperations : CORBA.IValueDefOperations
	{
		[IdlName("ext_initializers")]
		public CORBA.ExtInitializer[] ExtInitializers 
		{
			get;

			set;
		}
		[IdlName("describe_ext_value")]
		public CORBA.ExtValueDef.ExtFullValueDescription DescribeExtValue();
		[IdlName("create_ext_attribute")]
		public CORBA.IExtAttributeDef CreateExtAttribute([WideChar(false)] string id, [WideChar(false)] string name, [WideChar(false)] string version, CORBA.IIDLType type, CORBA.AttributeMode mode, CORBA.IExceptionDef[] getExceptions, CORBA.IExceptionDef[] setExceptions);
	}
}

