/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("LocalInterfaceDef")]
	[RepositoryID("IDL:CORBA/LocalInterfaceDef:1.0")]
	[Helper(typeof(LocalInterfaceDefHelper))]
	[Stub(typeof(_LocalInterfaceDefStub))]
	public interface ILocalInterfaceDef : CORBA.IIDLEntity, CORBA.IObject, ILocalInterfaceDefOperations, CORBA.IInterfaceDef
	{
	}
}

