/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("OperationDef")]
	[RepositoryID("IDL:CORBA/OperationDef:1.0")]
	[Helper(typeof(OperationDefHelper))]
	[Stub(typeof(_OperationDefStub))]
	public interface IOperationDef : CORBA.IIDLEntity, CORBA.IObject, IOperationDefOperations, CORBA.IContained
	{
	}
}

