/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("Repository")]
	[RepositoryID("IDL:CORBA/Repository:1.0")]
	[Helper(typeof(RepositoryHelper))]
	[Stub(typeof(_RepositoryStub))]
	public interface IRepository : CORBA.IIDLEntity, CORBA.IObject, IRepositoryOperations, CORBA.IContainer
	{
	}
}

