/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("UnionDef")]
	[RepositoryID("IDL:CORBA/UnionDef:1.0")]
	[Helper(typeof(UnionDefHelper))]
	[Stub(typeof(_UnionDefStub))]
	public interface IUnionDef : CORBA.IIDLEntity, CORBA.IObject, IUnionDefOperations, CORBA.ITypedefDef, CORBA.IContainer
	{
	}
}

