/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:32:22
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CORBA
{
	[RepositoryID("IDL:CORBA/ModuleDescription:1.0")]
	[Helper(typeof(ModuleDescriptionHelper))]
	public partial class ModuleDescription: CORBA.IIDLEntity, IEquatable<CORBA.ModuleDescription>
	{
		[IdlName("name")]
		[WideChar(false)]
		public string Name { get; set; }
		[IdlName("id")]
		[WideChar(false)]
		public string Id { get; set; }
		[IdlName("defined_in")]
		[WideChar(false)]
		public string DefinedIn { get; set; }
		[IdlName("version")]
		[WideChar(false)]
		public string Version { get; set; }

		public ModuleDescription()
		{
		}

		public ModuleDescription(ModuleDescription other)
		{
			Name = other.Name;
			Id = other.Id;
			DefinedIn = other.DefinedIn;
			Version = other.Version;
		}

		public ModuleDescription(string name, string id, string definedIn, string version)
		{
			this.Name = name;
			this.Id = id;
			this.DefinedIn = definedIn;
			this.Version = version;
		}

		public bool Equals(CORBA.ModuleDescription? other)
		{
			if (other == null) return false;
			if (!Name.Equals(other.Name)) return false;
			if (!Id.Equals(other.Id)) return false;
			if (!DefinedIn.Equals(other.DefinedIn)) return false;
			if (!Version.Equals(other.Version)) return false;
			return true;
		}
	}

}
