/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("SetOverrideType")]
	[RepositoryID("IDL:CORBA/SetOverrideType:1.0")]
	[Helper(typeof(SetOverrideTypeHelper))]
	public enum SetOverrideType
	{
		[IdlName("SET_OVERRIDE")]
		SET_OVERRIDE = 0,
		[IdlName("ADD_OVERRIDE")]
		ADD_OVERRIDE = 1,
	}

}
