/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
		public static class StructDefHelper
		{
			private static volatile CORBA.TypeCode type;

			public static CORBA.TypeCode Type()
			{
				if (type == null)
				{
					lock (typeof(StructDefHelper))
					{
						if (type == null)
						{
							type = CORBA.ORB.Init().CreateInterfaceTc("IDL:CORBA/StructDef:1.0", "StructDef");
						}
					}
				}
				return type;
			}

			public static void Insert(CORBA.Any any, CORBA.IStructDef ifz)
			{
				any.InsertObject(ifz);
			}

			public static CORBA.IStructDef Extract(CORBA.Any any)
			{
				return Narrow(any.ExtractObject());
			}

			public static string Id()
			{
				return "IDL:CORBA/StructDef:1.0";
			}

			public static CORBA.IStructDef Read(CORBA.IInputStream inputStream)
			{
				return Narrow(inputStream.ReadObject(typeof(_StructDefStub)));
			}

			public static void Write(CORBA.IOutputStream outputStream, CORBA.IStructDef ifz)
			{
				outputStream.WriteObject(ifz);
			}

			public static CORBA.IStructDef Narrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IStructDef)
				{
					return (CORBA.IStructDef)obj;
				}
				else if (obj._IsA("IDL:CORBA/StructDef:1.0"))
				{
					_StructDefStub stub = new _StructDefStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
				else
				{
					throw new CORBA.BadParam("Narrow failed");
				}
			}

			public static CORBA.IStructDef UncheckedNarrow(CORBA.IObject obj)
			{
				if (obj == null)
				{
					return null;
				}
				else if (obj is CORBA.IStructDef)
				{
					return (CORBA.IStructDef)obj;
				}
				else
				{
					_StructDefStub stub = new _StructDefStub();
					stub._Delegate = ((CORBA.Object)obj)._Delegate;
					return stub;
				}
			}
		}
}
