/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace ZIOP
{
	[IdlName("COMPRESSOR_ID_LEVEL_LIST_POLICY_ID")]
	public sealed class COMPRESSOR_ID_LEVEL_LIST_POLICY_ID
	{
		public const uint Value = 65;
	}
}
