/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:37
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace ZIOP
{
	[IdlName("CompressionEnablingPolicy")]
	[RepositoryID("IDL:omg.org/ZIOP/CompressionEnablingPolicy:1.0")]
	[Helper(typeof(CompressionEnablingPolicyHelper))]
	[Stub(typeof(_CompressionEnablingPolicyLocalBase))]
	public interface ICompressionEnablingPolicy : CORBA.IIDLEntity, CORBA.ILocalInterface, ICompressionEnablingPolicyOperations, CORBA.IPolicy
	{
	}
}

