/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace IOP
{
	[IdlName("Codec")]
	[RepositoryID("IDL:IOP/Codec:1.0")]
	[Helper(typeof(CodecHelper))]
	[Stub(typeof(_CodecLocalBase))]
	public interface ICodec : CORBA.IIDLEntity, CORBA.ILocalInterface, ICodecOperations
	{
	}
}

