/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace IOP
{
	[IdlName("TAG_DCE_SEC_MECH")]
	public sealed class TAG_DCE_SEC_MECH
	{
		public const uint Value = 103;
	}
}
