/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace IOP
{
	public static class TaggedProfileHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(TaggedProfileHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(IOP.TaggedProfileHelper.Id(), "TaggedProfile", new CORBA.StructMember[] {new CORBA.StructMember("tag", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 5), null), new CORBA.StructMember("profile_data", CORBA.ORB.Init().CreateSequenceTc(0, CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 10)), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, IOP.TaggedProfile s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static IOP.TaggedProfile Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:IOP/TaggedProfile:1.0";
		}

		public static IOP.TaggedProfile Read(CORBA.IInputStream inputStream)
		{
			var result = new IOP.TaggedProfile();
			result.Tag = inputStream.ReadULong();
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				var _array = new byte[_capacity0];
				inputStream.ReadOctetArray(ref _array, 0, _capacity0);
				result.ProfileData = _array;
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, IOP.TaggedProfile s)
		{
			outputStream.WriteULong(s.Tag);
			{
				outputStream.WriteLong(s.ProfileData.Length);
				outputStream.WriteOctetArray(s.ProfileData, 0, s.ProfileData.Length);
			}
		}

	}
}
