/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 26/02/2024 12:18:44
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Test
{
	[IdlName("Recursive")]
	[RepositoryID("IDL:Test/Recursive:1.0")]
	[Helper(typeof(RecursiveHelper))]
	[Stub(typeof(_RecursiveStub))]
	public interface IRecursive : CORBA.IIDLEntity, CORBA.IObject, IRecursiveOperations
	{
	}
}

