/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Security
{
	public static class AttributeListHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(AttributeListHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(Security.AttributeListHelper.Id(), "AttributeList", CORBA.ORB.Init().CreateSequenceTc(0, Security.SecAttributeHelper.Type()));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Security.SecAttribute[] value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static Security.SecAttribute[] Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/Security/AttributeList:1.0";
		}

		public static Security.SecAttribute[] Read(CORBA.IInputStream inputStream)
		{
			Security.SecAttribute[] result;
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				result = new Security.SecAttribute[_capacity0];
				for (int i0 = 0; i0 < _capacity0; i0++)
				{
					Security.SecAttribute _item0;
					_item0 = Security.SecAttributeHelper.Read(inputStream);
					result[i0] = _item0;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, Security.SecAttribute[] value)
		{
			{
				outputStream.WriteLong(value.Length);
				for (int i0 = 0; i0 < value.Length; i0++)
				{
					Security.SecAttributeHelper.Write(outputStream, value[i0]);
				}
			}
		}

	}
}
