/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Security
{
	public static class IntervalTHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(IntervalTHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(Security.IntervalTHelper.Id(), "IntervalT", TimeBase.IntervalTHelper.Type());
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, TimeBase.IntervalT value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static TimeBase.IntervalT Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/Security/IntervalT:1.0";
		}

		public static TimeBase.IntervalT Read(CORBA.IInputStream inputStream)
		{
			TimeBase.IntervalT result;
			result = TimeBase.IntervalTHelper.Read(inputStream);
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, TimeBase.IntervalT value)
		{
			TimeBase.IntervalTHelper.Write(outputStream, value);
		}

	}
}
