/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Security
{
	public static class MechandOptionsHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(MechandOptionsHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(Security.MechandOptionsHelper.Id(), "MechandOptions", new CORBA.StructMember[] {new CORBA.StructMember("mechanism_type", CORBA.ORB.Init().CreateStringTc(0), null), new CORBA.StructMember("options_supported", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 2), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Security.MechandOptions s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static Security.MechandOptions Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/Security/MechandOptions:1.0";
		}

		public static Security.MechandOptions Read(CORBA.IInputStream inputStream)
		{
			var result = new Security.MechandOptions();
			result.MechanismType = inputStream.ReadString();
			result.OptionsSupported = inputStream.ReadUShort();
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, Security.MechandOptions s)
		{
			outputStream.WriteString(s.MechanismType);
			outputStream.WriteUShort(s.OptionsSupported);
		}

	}
}
