/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Security
{
	public static class OptionsDirectionPairListHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(OptionsDirectionPairListHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateAliasTc(Security.OptionsDirectionPairListHelper.Id(), "OptionsDirectionPairList", CORBA.ORB.Init().CreateSequenceTc(0, Security.OptionsDirectionPairHelper.Type()));
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Security.OptionsDirectionPair[] value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static Security.OptionsDirectionPair[] Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/Security/OptionsDirectionPairList:1.0";
		}

		public static Security.OptionsDirectionPair[] Read(CORBA.IInputStream inputStream)
		{
			Security.OptionsDirectionPair[] result;
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				result = new Security.OptionsDirectionPair[_capacity0];
				for (int i0 = 0; i0 < _capacity0; i0++)
				{
					Security.OptionsDirectionPair _item0;
					_item0 = Security.OptionsDirectionPairHelper.Read(inputStream);
					result[i0] = _item0;
				}
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, Security.OptionsDirectionPair[] value)
		{
			{
				outputStream.WriteLong(value.Length);
				for (int i0 = 0; i0 < value.Length; i0++)
				{
					Security.OptionsDirectionPairHelper.Write(outputStream, value[i0]);
				}
			}
		}

	}
}
