/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:29
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace Security
{
	public static class RightsCombinatorHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(RightsCombinatorHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateEnumTc(Security.RightsCombinatorHelper.Id(),"RightsCombinator", new String[] {"SecAllRights", "SecAnyRight"});
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, Security.RightsCombinator value)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), value);
		}

		public static Security.RightsCombinator Extract(CORBA.Any any)
		{
				var inputStream = any.CreateInputStream();
			try
			{
			return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:omg.org/Security/RightsCombinator:1.0";
		}

		public static Security.RightsCombinator Read(CORBA.IInputStream inputStream)
		{
			return (Security.RightsCombinator) inputStream.ReadLong();
		}

		public static void Write(CORBA.IOutputStream outputStream, Security.RightsCombinator value)
		{
			outputStream.WriteLong((int) value);
		}

	}
}
