/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	public abstract class _PolicyManagerLocalBase: CORBA.LocalObject, IPolicyManager
	{
		private string[] _ids = {"IDL:CORBA/PolicyManager:1.0"};

		public override string[] _Ids()
		{
			return _ids;
		}

		[IdlName("get_policy_overrides")]
		public abstract CORBA.IPolicy[] GetPolicyOverrides(uint[] ts);
		[IdlName("set_policy_overrides")]
		[ThrowsIdlException(typeof(CORBA.InvalidPolicies))]
		public abstract void SetPolicyOverrides(CORBA.IPolicy[] policies, CORBA.SetOverrideType setAdd);
	}

}
