/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CORBA
{
	[IdlName("BAD_POLICY")]
	public sealed class BAD_POLICY
	{
		public const short Value = 0;
	}
}
