/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CORBA
{
	[RepositoryID("IDL:CORBA/ConstantDescription:1.0")]
	[Helper(typeof(ConstantDescriptionHelper))]
	public partial class ConstantDescription: CORBA.IIDLEntity, IEquatable<CORBA.ConstantDescription>
	{
		[IdlName("ConstantDescription")]
		[WideChar(false)]
		public string Name { get; set; }
		[IdlName("ConstantDescription")]
		[WideChar(false)]
		public string Id { get; set; }
		[IdlName("ConstantDescription")]
		[WideChar(false)]
		public string DefinedIn { get; set; }
		[IdlName("ConstantDescription")]
		[WideChar(false)]
		public string Version { get; set; }
		[IdlName("ConstantDescription")]
		public CORBA.TypeCode Type { get; set; }
		[IdlName("ConstantDescription")]
		public CORBA.Any Value { get; set; }

		public ConstantDescription()
		{
		}

		public ConstantDescription(ConstantDescription other)
		{
			Name = other.Name;
			Id = other.Id;
			DefinedIn = other.DefinedIn;
			Version = other.Version;
			Type = other.Type;
			Value = other.Value;
		}

		public ConstantDescription(string name, string id, string definedIn, string version, CORBA.TypeCode type, CORBA.Any value)
		{
			this.Name = name;
			this.Id = id;
			this.DefinedIn = definedIn;
			this.Version = version;
			this.Type = type;
			this.Value = value;
		}

		public bool Equals(CORBA.ConstantDescription? other)
		{
			if (other == null) return false;
			if (!Name.Equals(other.Name)) return false;
			if (!Id.Equals(other.Id)) return false;
			if (!DefinedIn.Equals(other.DefinedIn)) return false;
			if (!Version.Equals(other.Version)) return false;
			if (!Type.Equals(other.Type)) return false;
			if (!Value.Equals(other.Value)) return false;
			return true;
		}
	}

}
