/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CORBA
{
	[RepositoryID("IDL:CORBA/ExtInitializer:1.0")]
	[Helper(typeof(ExtInitializerHelper))]
	public partial class ExtInitializer: CORBA.IIDLEntity, IEquatable<CORBA.ExtInitializer>
	{
		[IdlName("ExtInitializer")]
		public CORBA.StructMember[] Members { get; set; }
		[IdlName("ExtInitializer")]
		public CORBA.ExceptionDescription[] Exceptions { get; set; }
		[IdlName("ExtInitializer")]
		[WideChar(false)]
		public string Name { get; set; }

		public ExtInitializer()
		{
		}

		public ExtInitializer(ExtInitializer other)
		{
			Members = other.Members;
			Exceptions = other.Exceptions;
			Name = other.Name;
		}

		public ExtInitializer(CORBA.StructMember[] members, CORBA.ExceptionDescription[] exceptions, string name)
		{
			this.Members = members;
			this.Exceptions = exceptions;
			this.Name = name;
		}

		public bool Equals(CORBA.ExtInitializer? other)
		{
			if (other == null) return false;
			if (!Members.SequenceEqual(other.Members)) return false;
			if (!Exceptions.SequenceEqual(other.Exceptions)) return false;
			if (!Name.Equals(other.Name)) return false;
			return true;
		}
	}

}
