/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:17
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("AbstractInterfaceDef")]
	[RepositoryID("IDL:CORBA/AbstractInterfaceDef:1.0")]
	[Helper(typeof(AbstractInterfaceDefHelper))]
	[Stub(typeof(_AbstractInterfaceDefStub))]
	public interface IAbstractInterfaceDef : CORBA.IIDLEntity, CORBA.IObject, IAbstractInterfaceDefOperations, CORBA.IInterfaceDef
	{
	}
}

