/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("ExceptionDef")]
	[RepositoryID("IDL:CORBA/ExceptionDef:1.0")]
	[Helper(typeof(ExceptionDefHelper))]
	[Stub(typeof(_ExceptionDefStub))]
	public interface IExceptionDef : CORBA.IIDLEntity, CORBA.IObject, IExceptionDefOperations, CORBA.IContained, CORBA.IContainer
	{
	}
}

