/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("ExtLocalInterfaceDef")]
	[RepositoryID("IDL:CORBA/ExtLocalInterfaceDef:1.0")]
	[Helper(typeof(ExtLocalInterfaceDefHelper))]
	[Stub(typeof(_ExtLocalInterfaceDefStub))]
	public interface IExtLocalInterfaceDef : CORBA.IIDLEntity, CORBA.IObject, IExtLocalInterfaceDefOperations, CORBA.ILocalInterfaceDef, CORBA.IInterfaceAttrExtension
	{
	}
}

