/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:27
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	public interface IFixedDefOperations : CORBA.IIDLTypeOperations
	{
		[IdlName("digits")]
		public ushort Digits 
		{
			get;

			set;
		}
		[IdlName("scale")]
		public short Scale 
		{
			get;

			set;
		}
	}
}

