/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CORBA
{
	[RepositoryID("IDL:CORBA/Initializer:1.0")]
	[Helper(typeof(InitializerHelper))]
	public partial class Initializer: CORBA.IIDLEntity, IEquatable<CORBA.Initializer>
	{
		[IdlName("members")]
		public CORBA.StructMember[] Members { get; set; }
		[IdlName("name")]
		[WideChar(false)]
		public string Name { get; set; }

		public Initializer()
		{
		}

		public Initializer(Initializer other)
		{
			Members = other.Members;
			Name = other.Name;
		}

		public Initializer(CORBA.StructMember[] members, string name)
		{
			this.Members = members;
			this.Name = name;
		}

		public bool Equals(CORBA.Initializer? other)
		{
			if (other == null) return false;
			if (!Members.SequenceEqual(other.Members)) return false;
			if (!Name.Equals(other.Name)) return false;
			return true;
		}
	}

}
