/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{

	public class InterfaceAttrExtensionPOATie: InterfaceAttrExtensionPOA
	{
		public IInterfaceAttrExtensionOperations _OperationsDelegate { get; set; }
		private PortableServer.IPOA _poa;

		public InterfaceAttrExtensionPOATie(IInterfaceAttrExtensionOperations d)
		{
			_OperationsDelegate = d;
		}

		public InterfaceAttrExtensionPOATie(IInterfaceAttrExtensionOperations d, PortableServer.POA poa)
		{
			_OperationsDelegate = d;
			_poa = poa;
		}

		public override PortableServer.IPOA _DefaultPOA()
		{
			if (_poa != null)
			{
				return _poa;
			}
			return base._DefaultPOA();
		}

		public override CORBA.IInterfaceAttrExtension _This()
		{
			return CORBA.InterfaceAttrExtensionHelper.Narrow(_ThisObject());
		}

		public override CORBA.IInterfaceAttrExtension _This(CORBA.ORB orb)
		{
			return CORBA.InterfaceAttrExtensionHelper.Narrow(_ThisObject(orb));
		}

		[IdlName("describe_ext_interface")]
		public override CORBA.InterfaceAttrExtension.ExtFullInterfaceDescription DescribeExtInterface()
		{
			return _OperationsDelegate.DescribeExtInterface();
		}
		[IdlName("create_ext_attribute")]
		public override CORBA.IExtAttributeDef CreateExtAttribute([WideChar(false)] string id, [WideChar(false)] string name, [WideChar(false)] string version, CORBA.IIDLType type, CORBA.AttributeMode mode, CORBA.IExceptionDef[] getExceptions, CORBA.IExceptionDef[] setExceptions)
		{
			return _OperationsDelegate.CreateExtAttribute(id, name, version, type, mode, getExceptions, setExceptions);
		}
	}
}
