/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("PolicyManager")]
	[RepositoryID("IDL:CORBA/PolicyManager:1.0")]
	[Helper(typeof(PolicyManagerHelper))]
	[Stub(typeof(_PolicyManagerLocalBase))]
	public interface IPolicyManager : CORBA.IIDLEntity, CORBA.ILocalInterface, IPolicyManagerOperations
	{
	}
}

