/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:17
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	public interface IPolicyOperations
	{
		[IdlName("policy_type")]
		public uint PolicyType 
		{
			get;
		}
		[IdlName("copy")]
		public CORBA.IPolicy Copy();
		[IdlName("destroy")]
		public void Destroy();
	}
}

