/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	public interface IUnionDefOperations : CORBA.ITypedefDefOperations, CORBA.IContainerOperations
	{
		[IdlName("discriminator_type")]
		public CORBA.TypeCode DiscriminatorType 
		{
			get;
		}
		[IdlName("discriminator_type_def")]
		public CORBA.IIDLType DiscriminatorTypeDef 
		{
			get;

			set;
		}
		[IdlName("members")]
		public CORBA.UnionMember[] Members 
		{
			get;

			set;
		}
	}
}

