/**
 * Generated by DotNetORb.IdlCompiler V 1.0.8.0
 * Timestamp: 31/03/2026 10:31:18
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	[IdlName("ValueMemberDef")]
	[RepositoryID("IDL:CORBA/ValueMemberDef:1.0")]
	[Helper(typeof(ValueMemberDefHelper))]
	[Stub(typeof(_ValueMemberDefStub))]
	public interface IValueMemberDef : CORBA.IIDLEntity, CORBA.IObject, IValueMemberDefOperations, CORBA.IContained
	{
	}
}

