/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace CORBA
{
	public static class ServiceDetailHelper
	{
		private static volatile CORBA.TypeCode type;

		public static CORBA.TypeCode Type()
		{
			if (type == null)
			{
				lock (typeof(ServiceDetailHelper))
				{
					if (type == null)
					{
						type = CORBA.ORB.Init().CreateStructTc(CORBA.ServiceDetailHelper.Id(), "ServiceDetail", new CORBA.StructMember[] {new CORBA.StructMember("service_detail_type", CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 5), null), new CORBA.StructMember("service_detail", CORBA.ORB.Init().CreateSequenceTc(0, CORBA.ORB.Init().GetPrimitiveTc((CORBA.TCKind) 10)), null), });
					}
				}
			}
			return type;
		}

		public static void Insert(CORBA.Any any, CORBA.ServiceDetail s)
		{
			any.Type = Type();
			Write(any.CreateOutputStream(), s);
		}

		public static CORBA.ServiceDetail Extract(CORBA.Any any)
		{
			var inputStream = any.CreateInputStream();
			try
			{
				return Read(inputStream);
			}
			finally
			{
				inputStream.Close();
			}
		}

		public static string Id()
		{
			return "IDL:CORBA/ServiceDetail:1.0";
		}

		public static CORBA.ServiceDetail Read(CORBA.IInputStream inputStream)
		{
			var result = new CORBA.ServiceDetail();
			result.ServiceDetailType = inputStream.ReadULong();
			{
				var _capacity0 = inputStream.ReadLong();
				if (inputStream.Available > 0 && _capacity0 > inputStream.Available)
				{
					throw new Marshal($"Sequence length too large. Only {inputStream.Available} and trying to assign {_capacity0}");
				}
				var _array = new byte[_capacity0];
				inputStream.ReadOctetArray(ref _array, 0, _capacity0);
				result._ServiceDetail = _array;
			}
			return result;
		}

		public static void Write(CORBA.IOutputStream outputStream, CORBA.ServiceDetail s)
		{
			outputStream.WriteULong(s.ServiceDetailType);
			{
				outputStream.WriteLong(s._ServiceDetail.Length);
				outputStream.WriteOctetArray(s._ServiceDetail, 0, s._ServiceDetail.Length);
			}
		}

	}
}
