/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;

namespace CORBA
{
	[RepositoryID("IDL:CORBA/StructMember:1.0")]
	[Helper(typeof(StructMemberHelper))]
	public partial class StructMember: CORBA.IIDLEntity, IEquatable<CORBA.StructMember>
	{
		[IdlName("StructMember")]
		[WideChar(false)]
		public string Name { get; set; }
		[IdlName("StructMember")]
		public CORBA.TypeCode Type { get; set; }
		[IdlName("StructMember")]
		public CORBA.IIDLType TypeDef { get; set; }

		public StructMember()
		{
		}

		public StructMember(StructMember other)
		{
			Name = other.Name;
			Type = other.Type;
			TypeDef = other.TypeDef;
		}

		public StructMember(string name, CORBA.TypeCode type, CORBA.IIDLType typeDef)
		{
			this.Name = name;
			this.Type = type;
			this.TypeDef = typeDef;
		}

		public bool Equals(CORBA.StructMember? other)
		{
			if (other == null) return false;
			if (!Name.Equals(other.Name)) return false;
			if (!Type.Equals(other.Type)) return false;
			if (!TypeDef.Equals(other.TypeDef)) return false;
			return true;
		}
	}

}
