/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RTCORBA
{
	[IdlName("PriorityBandedConnectionPolicy")]
	[RepositoryID("IDL:RTCORBA/PriorityBandedConnectionPolicy:1.0")]
	[Helper(typeof(PriorityBandedConnectionPolicyHelper))]
	[Stub(typeof(_PriorityBandedConnectionPolicyLocalBase))]
	public interface IPriorityBandedConnectionPolicy : CORBA.IIDLEntity, CORBA.ILocalInterface, IPriorityBandedConnectionPolicyOperations, CORBA.IPolicy
	{
	}
}

