/**
 * Generated by DotNetORb.IdlCompiler V 1.0.0.0
 * Timestamp: 25/02/2024 9:49:28
 *
 */

using System;
using System.Collections.Generic;
using System.Linq;
using CORBA;


namespace RTCORBA
{
	public interface IPriorityModelPolicyOperations : CORBA.IPolicyOperations
	{
		[IdlName("priority_model")]
		public RTCORBA.PriorityModel PriorityModel 
		{
			get;
		}
		[IdlName("server_priority")]
		public short ServerPriority 
		{
			get;
		}
	}
}

